version: '3.2'
services:
  remembrancer:
    image: "mysql:5.7.22"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  astronomican:
    image: "rabbitmq:3.7.7"
    restart: always
  cogitator:
    build:
      args:
        - settingsfile=/code/settings.yml
        - secretsdir=/etc/secrets
        - secretsfile=/etc/secrets/creds.yml
      context: https://github.com/itsgc/twitch-servitor.git#u/itsgc/permacodes
    environment:
      - OAUTH_REFRESH_TOKEN
    image: twitch-servitor
    depends_on:
      - remembrancer
    command: ["/code/wait-for-it.sh", "remembrancer:3306", "--", "uwsgi",
              "--enable-threads", "--uid", "www-data", "--gid",
              "www-data", "--ini", "/code/uwsgi.ini"]
    ports:
      - "127.0.0.1:9000:8080"
    volumes:
      - type: bind
        source: ../twitch-servitor/creds.yml
        target: /etc/secrets/creds.yml
  auscultator:
    image: twitch-servitor
    depends_on:
      - cogitator
    command: ["/usr/bin/env", "python", "/code/server-websocket.py"]
    ports:
      - "127.0.0.1:9080:8080"
  astropath:
    image: twitch-servitor
    depends_on:
      - astronomican
      - auscultator
    command: ["/code/wait-for-it.sh", "--timeout=30", "astronomican:5672", "--",
              "/code/wait-for-it.sh", "auscultator:8080", "--",
              "/usr/bin/env", "python", "/code/rabbitmq-receiver.py"]
#  tithe-collector:
#    image: twitch-servitor
#    environment:
#      - PUBSUB_SECRETS_FILE=/etc/secrets/pubsub_creds.yml
#    depends_on:
#    - astronomican
#    command: ["/code/wait-for-it.sh", "--timeout=30", "astronomican:5672", "--",
#              "/usr/bin/env", "python", "/code/pubsub.py"]
#    volumes:
#      - type: bind
#        source: ../twitch-servitor/creds.yml
#        target: /etc/secrets/creds.yml
#      - type: bind
#        source: ../twitch-servitor/pubsub_creds.yml
#        target: /etc/secrets/pubsub_creds.yml
  vigil:
    image: twitch-servitor
    depends_on:
    - astronomican
    command: ["/code/wait-for-it.sh", "--timeout=30", "astronomican:5672", "--",
              "/usr/bin/env", "python", "/code/vigil.py"]
    volumes:
      - type: bind
        source: ../twitch-servitor/creds.yml
        target: /etc/secrets/creds.yml
