version: '3.2'
services:
  remembrancer:
    image: "mysql:5.7.22"
    command: --default-authentication-plugin=mysql_native_password
    ports:
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  astropath:
    image: "rabbitmq:3.7.7"
    restart: always
  cogitator:
    build:
      args:
        - settingsfile=/code/settings.yml
        - secretsdir=/etc/secrets
        - secretsfile=/etc/secrets/creds.yml
      context: https://github.com/itsgc/twitch-servitor.git#u/itsgc/initial
    depends_on:
      - remembrancer
    ports:
      - "9000:8080"
    volumes:
      - type: bind
        source: ../twitch-servitor/creds.yml
        target: /etc/secrets/creds.yml
