version: '3'
services:
  remembrancer:
    image: "mysql:5.7.22"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - database
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  astropath:
    image: "rabbitmq:3.7.7"
    networks:
      - aqmp
    restart: always
  cogitator:
    build:
      args:
        - creds
        - settingsfile="/code/settings.yml"
        - secretsdir = "/etc/secrets"
        - secretsfile="/etc/secrets/creds.yml"
      context: https://github.com/itsgc/twitch-servitor.git#u/itsgc/initial
networks:
  aqmp:
  cogitator:
  database: